### ISSUE TITLE
Example code not working

### ISSUE THREAD

**Issue by muneswar** [krispo/angular-nvd3#29]
Hello,

I downloaded and tried to follow the same example as mentioned on the page, but it could not render the chart. I see there are exceptions from the line element.empty() of clearElement function;

Below is the exception:
TypeError: undefined is not a function
    at Object.scope.api.clearElement (http://localhost:9999/portal/app/lib/angularnvd3/angular-nvd3.js:163:37)
    at Object.scope.api.updateWithOptions (http://localhost:9999/portal/app/lib/angularnvd3/angular-nvd3.js:36:39)
    at Object.scope.api.refresh (http://localhost:9999/portal/app/lib/angularnvd3/angular-nvd3.js:31:39)
    at Object.fn (http://localhost:9999/portal/app/lib/angularnvd3/angular-nvd3.js:307:93)
    at Scope.$digest (http://localhost:9999/portal/app/lib/angular/angular.js:10569:27)
    at Scope.$apply (http://localhost:9999/portal/app/lib/angular/angular.js:10802:24)
    at done (http://localhost:9999/portal/app/lib/angular/angular.js:6937:45)
    at completeRequest (http://localhost:9999/portal/app/lib/angular/angular.js:7102:7)
    at XMLHttpRequest.xhr.onreadystatechange (http://localhost:9999/portal/app/lib/angular/angular.js:7058:11)

when I comment out the line, it worked fine. I am not sure what the problem was. Can you please help?

I am using angular routing, that is the only difference.

// Fully clear directive element
clearElement: function (){
                            element.find('.title').remove();
                            element.find('.subtitle').remove();
                            element.find('.caption').remove();
                            element.empty();
                            scope.chart = null;
  }

**Comment by NameFILIP** [comment]
Hey @muneswar, were you able to solve the issue?
